config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  

  # Defines the root path route ("/")
  # root "posts#index"
  root 'products#index'
  resources :products

  resource :cart, only: [:show] do
    post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: :add_to_cart
    delete 'remove_from_cart/:product_id', to: 'carts#remove_from_cart', as: :remove_from_cart
  end
  
  resource :checkout, only: [:show] do
    get 'show', to: 'checkouts#show', as: :show
    get 'checkout', to: 'checkouts#checkout', as: :checkout
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# App record
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# class Cart < ApplicationRecord
class Cart < ApplicationRecord
  belongs_to :user
  has_one :checkout
  has_and_belongs_to_many :products
end

app/models/checkout.rb
# class Checkout < ApplicationRecord
class Checkout < ApplicationRecord
  belongs_to :cart
end

app/models/product.rb
# frozen_string_literal: true

# Product Model
class Product < ApplicationRecord
  before_save :set_seller
  belongs_to :user
  has_one :cart_product
  has_one :cart, through: :cart_products
  has_one_attached :photo

  validates :description, :size, :condition, :brand, :price, :original_price, presence: true

  has_one_attached :photo

  def self.sorted_by(field)
    case field
    when 'Price: Low to High'
      Product.order(price: :asc)
    when 'Price: High to Low'
      Product.order(price: :desc)
    when 'Size: Small to Large'
      Product.order(size: :desc)
    when 'Size: Large to Small'
      Product.order(size: :asc)
    when 'Newest'
      Product.order(created_at: :desc)
    else
      Product.all
    end
  end

  def discount?
    return unless !price.nil? && !original_price.nil?
    return 0 if price >= original_price

    ((original_price - price) / original_price * 100).round(2)
  end

  private

  def set_seller
    self.seller = user.email if user
  end
end

app/models/user.rb
# class User < ApplicationRecord
class User < ApplicationRecord
  has_one :cart
  has_one :checkout, through: :cart
  has_many :products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@colgate\.edu\z/i, message: 'must be a Colgate email address' }

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
# class CartsController < ApplicationController
class CartsController < ApplicationController
  before_action :authenticate_user!
  def show
    @cart = current_user.cart || Cart.create(user: current_user)
    @total_price = @cart.products.sum('price')
    @cart_products = @cart.products
  end

  def add_to_cart
    product = Product.find(params[:product_id])
    cart = current_user.cart || Cart.create(user: current_user)
    if cart.products.include?(product)
      flash[:notice] = 'This product is already in your cart.'
    else
      cart.products << product
      flash[:notice] = 'Product successfully added to cart.'
    end

    redirect_to product_path(product)
  end

  def remove_from_cart
    product = Product.find(params[:product_id])
    current_user.cart&.products&.delete(product)
    flash[:notice] = 'Product removed from cart.'
    redirect_to cart_path(current_user.cart)
  end
end

app/controllers/checkouts_controller.rb
# Checkout Controller

class CheckoutsController < ApplicationController
  def show
    @cart = current_user.cart
    @cart = Cart.create(user: current_user) if @cart.nil?
    @checkout = Checkout.create(cart: @cart)
    @cart_products = @cart.products
    @total_price = @cart.products.sum('price')
  end

  def checkout
    @cart = current_user.cart
    @cart = Cart.create(user: current_user) if @cart.nil?
    @cart_products = @cart.products
    @cart_products.each(&:destroy)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Controller for clothing products
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def index
    @products = Product.all
    if session[:sort_by].present? || params[:sort_by].present?
      session[:sort_by] = params[:sort_by] || session[:sort_by]
      @products = Product.sorted_by(session[:sort_by])
    end

    if params[:search].present?
      @products = @products.where('lower(description) LIKE ?', "%#{params[:search].downcase}%")
    end
    @products
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def destroy
    @product = Product.find(params[:id])

    if @product.user == current_user
      @product.destroy
      flash[:notice] = 'Product successfully deleted'
    else
      flash[:alert] = 'You are not authorized to delete this product.'
    end
    redirect_to products_path
  end

  def create
    @product = current_user.products.build(create_update_params)
    @product.photo.attach(params[:product][:photo]) if params[:product][:photo].present?

    if @product.save
      flash[:notice] = 'Item successfully uploaded'
      redirect_to products_path and return
    else
      flash[:alert] = 'Upload failed'
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def create_update_params
    params.require(:product).permit(:description, :size, :condition, :brand, :price, :original_price, :photo)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# App Helper
module ApplicationHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# Products Helper
module ProductsHelper
end

app/views/carts/show.html.erb
<h1>Your Shopping Cart</h1>

<section id="main" class="container">

  <% if @cart_products.any? %>
      <table class = "table>
        <% @cart_products.each do |product| %>
          <tr class="product">
          <% if product.photo.attached? %>
            <td>
              <%= link_to product_path(product) do %>
                <%= image_tag product.photo, class: "product-image" %>
              <% end %>
              </td>
            <% else %>
              <td>
              <%= link_to product_path(product) do %>
                <%= image_tag 'download.png', class: "product-image" %>
              <% end %>
            </td>
            <% end %>
            <td><%= product.size %>
            <td><%= number_to_currency(product.price) %>
            <td><%= button_to 'Remove', remove_from_cart_cart_path(product), method: :delete, class: "btn product-action-btn" %>
        </tr>
      <% end %>
    </table>

    <p class = "total-price">Total Price: <%= number_to_currency(@total_price) %></p>
    <br> 
    <%= button_to "Checkout", show_checkout_path, method: :get, class: "btn cart-action-btn" %>
    <br>
  <% else %>
    <p>Your cart is empty.</p>
  <% end %>

  <br>
  <%= button_to "Back to Products", products_path, method: :get, class: "btn cart-action-btn" %>
  <br>
</section>

app/views/checkouts/_form_template.html.erb
<section class="checkout-form">
  <h3>Delivery Information</h3>
  <div>
    <%= checkout_form.label :first_name %>
    <%= checkout_form.text_field :first_name %>
  </div>

  <div>
    <%= checkout_form.label :last_name %>
    <%= checkout_form.text_field :last_name %>
  </div>

  <div>
    <%= checkout_form.label :shipping_address %>
    <%= checkout_form.text_field :shipping_address %>
  </div>


  <div>
    <%= checkout_form.label :city %>
    <%= checkout_form.text_field :city %>
  </div>

  <div>
    <%= checkout_form.label :state %>
    <%= checkout_form.select :state, ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 
                                      'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 
                                      'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 
                                      'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 
                                      'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'] %>
  </div>

  <div>
    <%= checkout_form.label :zip_code %>
    <%= checkout_form.text_field :zip_code %>
  </div>

  <div>
    <%= checkout_form.label :email %>
    <%= checkout_form.email_field :email %>
  </div>

  <div>
    <%= checkout_form.label :delivery_method %>
    <%= checkout_form.select :delivery_method, ['Standard Shipping', 'Express Shipping', 'Pickup'] %>
  </div>

  <h3>Payment Information</h3>

  <div>
    <%= checkout_form.label :card_holder %>
    <%= checkout_form.text_field :card_holder %>
  </div>

  <div>
    <%= checkout_form.label :credit_card_number %>
    <%= checkout_form.text_field :credit_card_number %>
  </div>

  <div>
    <%= checkout_form.label :expiration_date %>
    <%= checkout_form.text_field :expiration_date %>
  </div>

  <div>
    <%= checkout_form.label :CVV %>
    <%= checkout_form.text_field :CVV %>
  </div>
  <br>

  </section>

app/views/checkouts/checkout.html.erb
<section class="order-success">
<h1> Order Successful! </h1>
</section>
<div class="center-container">
<%= button_to "Back to Products", products_path, method: :get, class: "btn btn-primary order-action-btn" %>
</div>

app/views/checkouts/show.html.erb
<section>
  <h1>Checkout</h1>
  <div class="container">

  <%# in app/views/ckeckouts/show.html.erb %>
  <%= form_with model: @checkout do |checkout_form| %>

  <%= render partial: 'form_template', locals: {checkout_form: checkout_form} %>

  <% end %>
  </div>

  <div class="checkout-button-container">

  <br>
  <%= button_to "Place Order", checkout_checkout_path, method: :get, class: "btn btn-primary checkout-action-btn" %>
  <br>

  <br>
  <%= button_to "Back to Products", products_path, method: :get, class: "btn btn-primary checkout-action-btn" %>
  <br>

  <br> 
  <%= button_to "Back to Cart", cart_path, method: :get, class: "btn btn-primary checkout-action-btn" %>
  <br>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= stylesheet_link_tag 'application' %>
  <title>ClothingProject</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar navbar-light bg-light">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger sign-btn", form_class: "nav-link" %>
      <% else %>
        <%= button_to "Sign In", new_user_session_path, class: "btn btn-primary sign-btn", form_class: "nav-link" %>
      <% end %>
    </li>
  </ul>
</nav>


  <section id="flash" class="container">
    <% if flash[:notice] %>
      <div class="alert alert-primary">
        <%= "#{flash[:notice]}" %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-warning">
        <%= "#{flash[:alert]}" %>
      </div>
    <% end %>
  </section>

  <%= yield %>



  
</body>



</html>

app/views/products/_form_template.html.erb
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@product.errors.count, "error") %> prevented
    this item from being uploaded:
  </h2>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= product_form.label :description %>
<%= product_form.text_field :description %>
<br>

<%= product_form.label :size %>
<%= product_form.select :size, ['S', 'M', 'L'] %>
<br>

<%= product_form.label :condition %>
<%= product_form.select :condition, ['New','Barely Used', 'Used','Poor'] %>
<br>

<%= product_form.label :brand %>
<%= product_form.text_field :brand %>
<br>

<%= product_form.label :price %>
<%= product_form.number_field :price, step: 0.01 %>
<br>

<%= product_form.label :original_price %>
<%= product_form.number_field :original_price, step: 0.01 %>
<br>
<%= product_form.label :photo %>
<%= product_form.file_field :photo %>
<br>
<%= product_form.submit %>

app/views/products/index.html.erb
<head>
<%= stylesheet_link_tag 'application' %>
</head>
<body>
  <header>
    <h1>Colgate Off the RAC</h1>
  </header>

<section id="main1" class="container">
  <h2 class="lead">Clothing Available for Purchase</p>
  <%= form_tag products_path, method: :get do %>
    <%= select_tag :sort_by, options_for_select(['Price: Low to High', 'Price: High to Low', 'Size: Small to Large', 'Size: Large to Small', 'Newest'],session[:sort]) %>
    <%= submit_tag 'Sort' %>
  <% end %>

  <%= form_tag products_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search by description" %>
    <%= submit_tag 'Search' %>
    <% if params[:search].present? %>
    <%= link_to 'Clear Search', products_path, class: 'btn btn-secondary' %>
    <% end %>
  <% end %>
  <br>
  <div class="product-grid">
  <% @products.each do |product| %>
    <div class="product">
      <% if product.photo.attached? %>
        <%= link_to product_path(product) do %>
          <%= image_tag product.photo, class: "img-fluid homepage-image" %>
        <% end %>
      <% else %>
        <%= link_to product_path(product) do %>
          <%= image_tag 'download.png', class: "img-fluid homepage-image" %>
        <% end %>
      <% end %>
      <p><%= product.size %></p>
      <p><%= number_to_currency(product.price) %></p>
    </div>
  <% end %>
</div>
  <br>
  <%= button_to "Add new item", new_product_path, method: :get, class: "btn btn-secondary product-action-btn" %>

  <br>
  <%= button_to 'View Cart', cart_path, method: :get, class: "btn btn-info product-action-btn" %>

</section>

</body>

app/views/products/new.html.erb
<div class="container">

<%# in app/views/products/new.html.erb %>
<%= form_with model: @product do |product_form| %>

  <%= render partial: 'form_template', locals: {product_form: product_form} %>

<% end %>
</div>

app/views/products/show.html.erb
<h1><%= @product.description %></h1>

<section id="main" class="container">
<div class="left-side">
  <h4>Product details </h4>
  <dl>
    <dt>Size
      <dd><%= @product.size %>
    <dt>Condition
      <dd><%= @product.condition %>
    <dt>Brand
      <dd><%= @product.brand %>
    <dt>Price
      <dd><%= number_to_currency(@product.price) %>
    <dt>Original Price
      <dd><%= number_to_currency(@product.original_price) %>
    <dt> Discount 
      <dd> <%=  @product.discount?.to_i %> % off!
    <dt>Seller
      <dd><%= @product.seller %>
  </dl>
</div>
<div class="right-side">
  <% if @product.photo.attached? %>
    <%= image_tag @product.photo, class: "img-fluid product-image" %>
  <% else %>
    <%= image_tag 'download.png', class: "img-fluid product-image" %>
  <% end %>
</div>
</section>


<div class="product-button-container">
    <%= button_to "Back to Products", products_path, method: :get, class: "btn btn-primary product-action-btn" %>
    <%= button_to "Delete this product", product_path(@product), method: :delete, class: "btn btn-danger product-action-btn" %>
    <%= button_to 'Add to Cart', add_to_cart_cart_path(@product), method: :post, class: "btn btn-success product-action-btn" %>
    <%= button_to 'View Cart', cart_path, method: :get, class: "btn btn-info product-action-btn" %>


  </div>
</section>